version: "3.2"
services:
  web:
    # replace username/repo:tag with your name and image details
    image: talalmts/backend:latest
    deploy:
      mode: replicated
      replicas: 5
      restart_policy:
        condition: on-failure
      placement:
        constraints: ["node.hostname != mystack-frontend"]
    ports:
      - "8000:80"
    volumes:
      - /etc:/hypervisor_etc
