version: "3.2"
services:
  web:
    # replace username/repo:tag with your name and image details
    image: talalmts/frontend:latest
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.hostname == mystack-frontend
    environment:
      - CC_BACKEND_SERVERS=$LC_BACKEND_IPS
    ports:
      - "80:80"
    volumes:
      - /etc:/hypervisor_etc
